# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-28 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_payment_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='accounts_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
