# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-12-03 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_payment_accounts_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='accounts_verified_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
