# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-12-03 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_payment_accounts_verified_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'permissions': (('verify_payment', 'Verify payment'),)},
        ),
    ]
