# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-10 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20181216_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='mode',
            field=models.CharField(choices=[('CA', 'Cash'), ('BT', 'Bank Transfer'), ('Swipe', 'SW'), ('Payslip', 'PS'), ('Paid to driver', 'PTD'), ('Department', 'DPT'), ('Pay on arrival', 'POA'), ('Complimentary', 'CPL')], default='CA', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, choices=[('WAT', 'Waiting'), ('STR', 'Started'), ('SUC', 'Success'), ('CAN', 'Cancelled'), ('ABT', 'Aborted'), ('RFN', 'Refunded'), ('FAL', 'Failure'), ('ERR', 'Error')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Income'), (-1, 'Driver pay')], default=1),
        ),
    ]