# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-10 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20190210_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='mode',
            field=models.CharField(choices=[('CA', 'Cash'), ('BT', 'Bank Transfer'), ('PG', 'Payment Gateway')], default='CA', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Income'), (-1, 'Expenditure')], default=1),
        ),
    ]
