# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('OW', 'One way'), ('RT', 'Round trip')], max_length=2)),
                ('travel_datetime', models.DateTimeField()),
                ('customer_name', models.CharField(db_index=True, max_length=100)),
                ('customer_mobile', models.CharField(db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('0', 'Request'), ('1', 'Confirmed'), ('2', 'Declined')], default='0', max_length=1)),
                ('payment_status', models.CharField(blank=True, choices=[('REC', 'Received'), ('DUE', 'Due')], max_length=3, null=True)),
                ('payment_mode', models.CharField(blank=True, choices=[('CA', 'Cash')], max_length=2, null=True)),
                ('extra_info', models.TextField(blank=True, default='')),
                ('pnr', models.CharField(blank=True, db_index=True, editable=False, max_length=20, unique=True)),
                ('total_fare', models.PositiveIntegerField(blank=True, default=0)),
                ('fare_details', models.TextField(blank=True, default='{}')),
                ('distance', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('mobile', models.CharField(db_index=True, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oneway_price', models.PositiveIntegerField()),
                ('oneway_distance', models.PositiveIntegerField()),
                ('oneway_driver_charge', models.PositiveIntegerField()),
                ('roundtrip_price', models.PositiveIntegerField(blank=True, default=0)),
                ('roundtrip_distance', models.PositiveIntegerField(blank=True, default=0)),
                ('roundtrip_driver_charge', models.PositiveIntegerField(blank=True, default=0)),
                ('code', models.CharField(blank=True, db_index=True, editable=False, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_destination', to='opencabs.Place')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_source', to='opencabs.Place')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('number', models.CharField(db_index=True, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, default='', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleRateCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, unique=True)),
                ('description', models.TextField(blank=True, default='', max_length=200)),
                ('tariff_per_km', models.PositiveIntegerField()),
                ('tariff_after_hours', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opencabs.VehicleCategory')),
                ('features', models.ManyToManyField(blank=True, to='opencabs.VehicleFeature')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opencabs.VehicleCategory'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='opencabs.Driver'),
        ),
        migrations.AddField(
            model_name='rate',
            name='vehicle_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='opencabs.VehicleRateCategory'),
        ),
        migrations.AddField(
            model_name='booking',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_destination', to='opencabs.Place'),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='opencabs.Driver'),
        ),
        migrations.AddField(
            model_name='booking',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_source', to='opencabs.Place'),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='opencabs.Vehicle'),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='opencabs.VehicleRateCategory'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicleratecategory',
            unique_together=set([('name', 'category')]),
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together=set([('code', 'vehicle_category')]),
        ),
    ]
