# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opencabs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='pnr',
            new_name='booking_id',
        ),
    ]
