# Generated by Django 3.0.4 on 2021-11-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencabs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='drivers',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('POA', 'Pay on arrival'), ('DPT', 'Department'), ('ONL', 'Online')], default='', max_length=3, null=True),
        ),
    ]
