# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencabs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecategory',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
