# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencabs', '0002_vehiclecategory_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclecategory',
            name='code',
        ),
        migrations.AddField(
            model_name='rate',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
