# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencabs', '0002_auto_20170209_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='oneway_distance',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
