# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencabs', '0003_auto_20170209_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pickup_point',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
