# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opencabs', '0003_auto_20170125_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='vehicle_category',
            new_name='vehicle',
        ),
    ]
