# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opencabs', '0004_auto_20170127_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opencabs.VehicleCategory')),
                ('driver', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='opencabs.Driver')),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('0', 'Request'), ('1', 'Confirmed'), ('2', 'Declined')], default='0', max_length=1),
        ),
    ]
