# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencabs', '0004_booking_pickup_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ssr',
            field=models.TextField(blank=True, default='', help_text='Special service request', max_length=200, verbose_name='Special service request'),
        ),
    ]
