# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencabs', '0005_auto_20170204_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
