# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opencabs', '0006_auto_20170204_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRateCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, default='', max_length=200)),
                ('tariff_per_km', models.PositiveIntegerField()),
                ('tariff_after_hours', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehiclecategory',
            name='created',
        ),
        migrations.RemoveField(
            model_name='vehiclecategory',
            name='features',
        ),
        migrations.RemoveField(
            model_name='vehiclecategory',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='vehiclecategory',
            name='tariff_after_hours',
        ),
        migrations.RemoveField(
            model_name='vehiclecategory',
            name='tariff_per_km',
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='opencabs.VehicleRateCategory'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='vehicle_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='opencabs.VehicleRateCategory'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='opencabs.Driver'),
        ),
        migrations.AlterField(
            model_name='vehiclecategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='vehicleratecategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opencabs.VehicleCategory'),
        ),
        migrations.AddField(
            model_name='vehicleratecategory',
            name='features',
            field=models.ManyToManyField(to='opencabs.VehicleFeature'),
        ),
    ]
