# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencabs', '0007_remove_booking_travel_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_mobile',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
    ]
