# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencabs', '0007_auto_20170204_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleratecategory',
            name='features',
            field=models.ManyToManyField(blank=True, null=True, to='opencabs.VehicleFeature'),
        ),
    ]
