# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencabs', '0009_auto_20170204_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='extrainfo',
        ),
        migrations.AddField(
            model_name='booking',
            name='extra_info',
            field=models.TextField(blank=True, default=''),
        ),
    ]
