# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencabs', '0009_auto_20170407_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_mode',
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_due',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('NP', 'Not paid'), ('PR', 'Partial'), ('PD', 'Paid')], default='NP', max_length=3, null=True),
        ),
    ]
