# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencabs', '0010_auto_20170429_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='driver_invoice_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='paid_to_driver',
            field=models.BooleanField(default=False),
        ),
    ]
