# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opencabs', '0010_auto_20170204_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='vehicle_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='opencabs.VehicleRateCategory'),
            preserve_default=False,
        ),
    ]
