# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencabs', '0011_auto_20170429_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='revenue',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
