# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencabs', '0012_rate_rental_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='rental_price',
        ),
        migrations.AddField(
            model_name='booking',
            name='distance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='fare_details',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('CA', 'Cash')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('REC', 'Received'), ('DUE', 'Due')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_fare',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('OW', 'One way')], max_length=2),
        ),
    ]
