# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencabs', '0013_auto_20170205_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='driver_charge',
        ),
        migrations.AddField(
            model_name='rate',
            name='oneway_distance',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rate',
            name='oneway_driver_charge',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rate',
            name='roundtrip_distance',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rate',
            name='roundtrip_driver_charge',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rate',
            name='roundtrip_price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('OW', 'One way'), ('RT', 'Round trip')], max_length=2),
        ),
        migrations.AlterField(
            model_name='vehicleratecategory',
            name='features',
            field=models.ManyToManyField(blank=True, to='opencabs.VehicleFeature'),
        ),
    ]
