# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencabs', '0014_auto_20170205_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='roundtrip_distance',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='rate',
            name='roundtrip_driver_charge',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='rate',
            name='roundtrip_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
