# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencabs', '0014_auto_20170429_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='accounts_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
