# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-10 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencabs', '0015_booking_accounts_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='revenue',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
