# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-23 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencabs', '0017_vehiclecategory_passengers'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='passengers',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
