# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-23 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opencabs', '0018_booking_passengers'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_paid', models.BooleanField(default=False)),
                ('driver_pay', models.PositiveIntegerField(blank=True, default=0)),
                ('driver_invoice_id', models.CharField(blank=True, max_length=50)),
                ('extra_info', models.TextField(blank=True, default='')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opencabs.Booking')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='opencabs.Driver')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='opencabs.Vehicle')),
            ],
        ),
    ]
