# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-24 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opencabs', '0020_auto_20180223_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='driver_invoice_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='driver_paid',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='driver_pay',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='extra_info',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='vehicle',
        ),
    ]
