# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-01 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opencabs', '0022_booking_vehicle_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_destination', to='opencabs.Place'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_source', to='opencabs.Place'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='opencabs.VehicleRateCategory'),
        ),
        migrations.AlterField(
            model_name='bookingvehicle',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='opencabs.Driver'),
        ),
        migrations.AlterField(
            model_name='bookingvehicle',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='opencabs.Vehicle'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rate_destination', to='opencabs.Place'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rate_source', to='opencabs.Place'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='vehicle_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rate', to='opencabs.VehicleRateCategory'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='opencabs.VehicleCategory'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='opencabs.Driver'),
        ),
        migrations.AlterField(
            model_name='vehicleratecategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='opencabs.VehicleCategory'),
        ),
    ]
