# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-29 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencabs', '0023_auto_20180301_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles'),
        ),
    ]
