# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-10 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencabs', '0026_auto_20190210_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('POA', 'Pay on arrival'), ('ONL', 'Online'), ('', '')], default='', max_length=3, null=True),
        ),
    ]
