# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-28 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencabs', '0027_auto_20190210_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='drivers',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
